### ISSUE TITLE
What to do if one cannot finish an exercise (Number 12 from #36)

### ISSUE THREAD

**Issue by biometrician** [jrckln/Bendyourspline#46]
Number 12 from #36:

If someone cannot solve one part of the exercise, there is currently no way to continue.

Q: Is this okay for us?

**Comment by ljiricka** [comment]
@georgheinze, @matherealize, @ChristineWallisch

**Comment by ChristineWallisch** [comment]
I think it is not really possible to jump over one task since they are built on each other. 
If you jump over one task, it might not be possible to do the next task either because you haven't made the correct settings from the previous step. We would have had to design different exercises with independent tasks.

**Comment by georgheinze** [comment]
what about a 'panic' or 'exit' button to jump out of the exercise
