### ISSUE TITLE
Let the game begin (Number 3 from #36)

### ISSUE THREAD

**Issue by biometrician** [jrckln/Bendyourspline#51]
Number 3 from #36 :

I was not involved in the discussions in the last year, so maybe my outlook is outdated, but nevertheless. 
The goal for the user is to "play" with the input parameters such that the response matches the optimal fit as good as possible. (Is this correct?) Like in a game. But this has to be declared somewhere. Somewhere at the beginning. Maybe even in the Home section!

**Comment by ljiricka** [comment]
This is the aim of some exercises but not all (see the basic exercises for Splines). We did not state this explicity since we do not focus on settings with data only but also on settings without data where the aim is to explore the behaviour of the response function without optimizing the current fit

**Comment by biometrician** [comment]
Okay, but don't we have to tell the audience what the goal is and what we expect them to do?

**Comment by ChristineWallisch** [comment]
In accordance with @georgheinze  we reformulated the exercises two weeks ago. They start now with a sentence about the aim of the exercise. You also got the email correspondance.
In addition, the help icons next to exercises also describe the general aim of the exercises. The most recent version with these features is available on the branch feat/help #55
